### ISSUE TITLE
Removing text does not work properly

### ISSUE THREAD

**Issue by RGNagel** [luoliyan/incremental-reading-for-anki#12]
I remove some sections of my cards by using the remove shortcut but when the cards show up again the removed section was not removed, it just there.
Also, sometimes I extract some sections to other IR Cards, then when they show up again they are not highlighted by 'extracted' color.

**Comment by luoliyan** [comment]
Hi,

Thanks for the report. I will look into this over the next few days.

**Comment by RGNagel** [comment]
I tried removing all other addons to check if any conflict issue could be the reason. However, the problem persist even after removing all addons but this one. 

I hope it will be useful somehow.

**Comment by RGNagel** [comment]
This problem is the same of issue [#4]. Highlight is not permanent and is broken at step 2.

**Comment by luoliyan** [comment]
Thanks for the information. Did you mean to close this issue?

A few other questions:
1. Does your IR3 front template contain `<div class="ir-text">{{Text}}</div>`?
2. Have you reinstalled the incremental reading add-on?
3. Are you using a Mac? (From memory, I think similar problems have only been reported by Mac users)
4. Are you able to confirm if this occurs with the [Anki 2.1 beta](https://apps.ankiweb.net/downloads/beta) and the [2.1-compatible add-on](https://github.com/luoliyan/incremental-reading-for-anki/archive/anki21.zip)? (Be careful if you try this, because Anki 2.1 moves all your data - which you might need to move back)

This kind of problem is the most difficult to investigate, because I'm not able to reproduce it locally. So I can't promise there'll be a solution for this, unless we can pin down the cause.

**Comment by RGNagel** [comment]
Before trying the steps above, I just removed anki (2.0.32) from my ubuntu and install the version 2.0.45 from anki web site. It did fix the problem according to my tests which allowed me to highlight and remove sections and they did not go away when reviewing the cards.

I appreciate your attention on this issue,
Thanks!
