### ISSUE TITLE
IR card scheduling 

### ISSUE THREAD

**Issue by mednerd** [luoliyan/incremental-reading-for-anki#18]
Hello, 
I am trying to figure out how to schedule my IR cards effectively. Basically, I want to be able to randomize the card order once and then maintain their position. Then I can see a card and choose to review it "soon", "later" or "much later" while still having the card order be initially randomized. If I could select all the cards in my reading organizer and hit "randomize" I think It would solve my problem. Also If i could somehow choose how to set scheduling for text that I extract from articles that would be amazing. Does that makes sense?

**Comment by luoliyan** [comment]
Yes, that makes sense, and it sounds like a good idea. Over the next few weeks, I need to overhaul the scheduling code in general, since there are some other issues with it.

I've barely touched that part of the code since I took over development of the add-on, so I can't say how long it'll take me. But I'll leave this issue open, and I'll post here again when I've got something for you.

**Comment by luoliyan** [comment]
I've implemented a randomisation feature in the rewritten organiser. Let me know if it works for you. I intend to add the "move to position" feature that the old organiser had, when I get some time.

As for setting the scheduling of extracted text, I'm not absolutely sure that would be useful. Unless someone can convince me that a decent use-case exists, it probably won't be implemented.

Feel free to open another issue if you have any trouble with this update.

**Comment by pkbs121** [comment]
Was that update applied to version 4? I haven't upgraded to 2.1 because many addons that are vital to me (image occlusion) aren't supported there yet. 

My thought with the scheduling of extracted cards was that.. at least for me.. If i am extracting from an article I want to see that portion of the article before I see the full one again.  So I was thinking if there was a setting like "move all extracted cards to 20% of the deck" that would let me do that. 

I experimented with removing IR and using my IR3 deck with custom set scheduling thru regular anki. This was great because I could really fine tune how I saw my cards. However, I lost many of the key aspects like extracting etc. Is it even remotely possible for me to remove the organizer and scheduling info from my IR addon, allowing me to handle that thru regular anki, yet still retain extraction and those aspects?

**Comment by luoliyan** [comment]
Okay, I can see the use in that. I thought you meant keying in a position for each card as you review it, which I don't think would be useful. I'll add that to my to-do list. I'll also think about back-porting some of this to v3 - but no promises.

At some stage I might add an option to disable the IR scheduler. Until then, you can comment out all of the lines from 468 to 473 in `main.py`. Just add a `#` character to the start of each line. That will leave you will the highlight, extract and delete keys, but the cards will be scheduled as regular Anki cards.

**Comment by luoliyan** [comment]
When you are done, the last few lines of `main.py` should look like this:
```
#Reviewer._answerButtonList = wrap(Reviewer._answerButtonList,
#                                  answerButtonList,
#                                  'around')

#Reviewer._answerCard = wrap(Reviewer._answerCard, answerCard, 'around')
#Reviewer._buttonTime = wrap(Reviewer._buttonTime, buttonTime, 'around')
Reviewer._keyHandler = wrap(Reviewer._keyHandler, keyHandler, 'around')
```
I haven't tested it, but I don't see any reason it wouldn't work.

**Comment by pkbs121** [comment]
Awesome. This appears to be working perfectly. Thanks!

**Comment by luoliyan** [comment]
I've back-ported the scheduler and organiser rewrite to v3, since that turned out to be remarkably easy. The IR scheduling should be more consistent now, and the organiser has the randomise feature.

I would appreciate any comments you have on it. I haven't updated it on AnkiWeb, but you can download it as a zip file [here](https://github.com/luoliyan/incremental-reading-for-anki/archive/legacy.zip).

**Comment by luoliyan** [comment]
In the development code for v4, you can now control the initial scheduling of extracts (e.g., move to 20% of deck). I may back-port this to v3 - but again, no promises.
