### ISSUE TITLE
Code to download AddOn is faulty in `README.md`

### ISSUE THREAD

**Issue by SebNag** [luoliyan/incremental-reading-for-anki#19]
Downloading the add on using the code provided in the `README.md` file fails with `Download failed: Error downloading: 404`. However, the one provided [here](https://ankiweb.net/shared/info/1081195335), `1081195335` works for installing conveniently. 

Just out of curiosity, I cannot find the add ons folder from anki to save the `ir` package manually. 
I installed anki in `/usr/local/share/anki/`.

**Comment by luoliyan** [comment]
Hi Sebastian,

Since you're using Anki 2.0, the older branch of IR is what you're looking for ([here](https://github.com/luoliyan/incremental-reading-for-anki/tree/legacy)). That page has instructions for locating your add-ons folder.

I believe you also were getting an error from IR because of the European character in your name. I've updated the add-on to address that. Just download the latest zip file ([here](https://github.com/luoliyan/incremental-reading-for-anki/archive/legacy.zip)) and let me know if that helps.
