### ISSUE TITLE
How to create the intial card for incremental reading ?

### ISSUE THREAD

**Issue by IbnSaeed** [luoliyan/incremental-reading-for-anki#29]
How to create the initial card for incremental reading ?

Should a new deck be created ?

I created a new deck and when i select "Organizer" it says "

> please select an incremental reading deck

How does this addon work ?

is there a guide ?

**Comment by luoliyan** [comment]
Hi Ibn Saeed,

Currently there isn't a guide, though I'd like to put one together some day.

The reason you're getting that message is because you don't have any incremental reading cards. The organizer won't open if there aren't any cards to organize.

Try to create a new card with the IR3 note type. Then practice adding shortcuts and creating regular SRS cards from your IR card. There is not much reason for you to use the organizer, until you have a large number of cards. Practice with the other features, and let me know if you get stuck.

**Comment by IbnSaeed** [comment]
ok thanks. Right now i am using supermemo for incremental reading.
