### ISSUE TITLE
RSS and/or «Pocket» sync.

### ISSUE THREAD

**Issue by JulyMorning** [luoliyan/incremental-reading-for-anki#8]
Please, could you implement a function to update reading list automatically? I've found this addon just right now and I was surprised that someone use this technique (it even has its own name). However, personally I really don't like to copypaste anything, wasting too much time. Is there a possibility to make it synchronize with RSS… For your reference:

— https://github.com/luminousspice/anki-addons (see «FeedToAnki»)

…or «Pocket» service? If you're not familiar with it, it's pretty mainstream tool to save articles you like to read them later. It's built into firefox by default and has a chrome addon.

— https://getpocket.com/

I hope it's possible. The pocket saves all the articles to its own domain, so all of them are unified to read/crawl by some beautifulSoup library or something like that.

**Comment by luoliyan** [comment]
Hi,

I started working on an RSS importer a while ago, and it's certainly something I'd like to share once it's ready. However, it's going to be another couple of months before I have a chance to finish it off - I'm bogged down with study at the moment.

I'll leave this issue open for now, and I'll post back here when I have an update.

Thanks for letting me know there's demand for this.

**Comment by JulyMorning** [comment]
hey, any news here? :3

**Comment by luoliyan** [comment]
Hi,

Sorry for the late reply. Exams took over my life for a while.

I plan to resume working on this sometime next week. I'll post here again when there's something to try.

**Comment by JulyMorning** [comment]
Although RSS would be fine, please, take a look at «pocket» service too. If the plug-in could parse it, it would be really-really awesome. Wish I could help, but I'm just a python newbie yet.

**Comment by luoliyan** [comment]
I agree with your argument. The only reason I plan to implement RSS first is because I've already written most of the code for it. I imagine there'd be a lot of overlap between the two anyway, so solving one problem should half-solve the other.

**Comment by JulyMorning** [comment]
hi there. I know, we all have some private things to do, but how is the progress on it? with rss and pocket your plugin would be a truefire.

**Comment by luoliyan** [comment]
Hi again. Thanks for your interest.

It took longer than expected to make the add-on compatible with Anki 2.1, and that was the first priority.

Once that was done, I added basic support for importing a webpage, since that code will be required for RSS import. The code for RSS has been (mostly) written, it just hasn't been incorporated into the add-on yet. I'm planning to have it done in the next couple of weeks.

Importing from Pocket will take a bit longer, since I need to write some UI code for that. Apart from that, it should share a lot of the code that's already been written.

**Comment by luoliyan** [comment]
Support for importing RSS has been added to the Anki 2.1 version. It's a little rough around the edges, but there aren't any major issues. As long as the URL starts with `http://` and the website doesn't reject a Python user agent, it seems to basically work. I tried 10 different feeds, and only 1 of them didn't work.

**Comment by JulyMorning** [comment]
Awesome, thanks. Can't wait for «pocket» support :3

**Comment by JulyMorning** [comment]
*checking this thread with great expectations*

**Comment by luoliyan** [comment]
This is 99% done. I will have something for you to test tomorrow, most likely.

This took such a long time because (a) Anki 2.1 hasn't completely stabilised, so I've been struggling just to keep the existing features working, (b) the Pocket API was a bit of a hurdle to figure out, and (c) I've been fairly busy with other things. But thanks for your continued interest.

**Comment by luoliyan** [comment]
This is implemented now. Please let me know how it goes.

At the moment, it can only be used to import the 10 newest articles in your reading list. I will need to put some options in menu, or allow the user to select which articles to import - but until then, can you just let me know if it _**basically**_ works?

**Comment by luoliyan** [comment]
I'm going to close this for now. I plan to move all the options into the menu at some stage, but it may not be for another month or so.

If you run into any bugs or have any feedback, feel free to open another issue.

**Comment by JulyMorning** [comment]
Just noticed your answer here. I'm going to test it this evening, and it's exiting to know that you've done with this feature. Thanks a lot.
